version: '3.8'

services:
  postgres:
    container_name: psql
    hostname: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tstdb
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 1s
      timeout: 1s
      retries: 2